title: Mapeo Estructural en Realidad Mixta
description: Sistema de teleoperación robótica con mapeo estructural y visualización en realidad mixta.
theme: just-the-docs

url: https://sebas30073007.github.io/mapeo-estructural-en-realidad-mixta

aux_links:
  GitHub: https://github.com/sebas30073007/mapeo-estructural-en-realidad-mixta

callouts_level: quiet
callouts:
  note:
    color: blue
  warning:
    color: yellow
